#!/usr/bin/env python
# vim: set fileencoding=utf-8 :
import datetime
import PyRSS2Gen
import json
import urllib2
import sys

reestr_json = urllib2.urlopen('http://api.antizapret.info/all.php?type=json').read()
reestr_json = open("test.json").read()

parsed=json.loads(reestr_json)

rss = PyRSS2Gen.RSS2(
    title = "Andrew's PyRSS2Gen feed",
    link = "http://www.dalkescientific.com/Python/PyRSS2Gen.html",
    description = "The latest news about PyRSS2Gen, a "
                  "Python library for generating RSS2 feeds",

    lastBuildDate = datetime.datetime.now(),

    items = []
    )

for item in parsed['register']:
    # print item['url']
    rss_item = PyRSS2Gen.RSSItem(
         title = item['url'],
         link = item['url'],
         description = u"свежак: %s, добавил %s" % (item['url'], item['org']),
         guid = PyRSS2Gen.Guid(item['proof']),
         pubDate = datetime.datetime(2003, 9, 6, 21, 31))

    rss.items.append(rss_item)

rss.write_xml(open("pyrss2gen.xml", "w"))
