#!/usr/bin/env python
# vim: set fileencoding=utf-8 :
import datetime
import PyRSS2Gen
import json
import urllib2

reestr_json = urllib2.urlopen('http://api.antizapret.info/all.php?type=json').read()
# reestr_json = open("test.json").read()

parsed=json.loads(reestr_json)

rss = PyRSS2Gen.RSS2(
    title = u"Свежие запрещённые сайты",
    link = "http://antizapret.info/",
    description = u"Свежие запрещённые сайты. Предназначено исключительно для мониторинга Реестра запрещенных сайтов, не является каталогом. Ограничение по возрасту - 18+",

    lastBuildDate = datetime.datetime.now(),

    items = []
    )

for item in parsed['register']:
    # print item['url']
    rss_item = PyRSS2Gen.RSSItem(
         title = item['url'],
         link = item['proof'],
         description = u"""<p><b>url:</b> <a href='%s'>%s</a>
            <p><b>домен: <a href='%s'>%s</a>
            <p><b>ip:</b> <a href='http://%s'>%s</a>
            <p><b>добавил информацию:</b> %s %s, приказ %s
            <p><b>включен в реестр:</b> %s
            """ % (item['url'], item['url'],
             item['domain'], item['domain'],
             item['ip'], item['ip'],
             item['rsocDate'], item['org'], item['org_act'],
             item['includeTime']
             ),
         guid = PyRSS2Gen.Guid(item['proof']),
         pubDate = item['includeTime']
         )

    rss.items.append(rss_item)

print rss.to_xml
